# from listas import Listas
# from recorrido_listas import RecorridoListas
from listas_simplemente_enlazadas import LinkedList


# inst_lista_mascotas = Listas()
# inst_recorrido_listas = RecorridoListas()
inst_single_linked_list = LinkedList()

inst_single_linked_list.add_node_at_end(1)
inst_single_linked_list.add_node_at_end(2)
inst_single_linked_list.add_node_at_end(3)
inst_single_linked_list.add_node_at_end(4)
inst_single_linked_list.add_node_at_end(5)
inst_single_linked_list.add_node_at_end(6)
inst_single_linked_list.add_node_at_start(7)

inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('Eliminar último nodo')
inst_single_linked_list.delete_at_end()
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('Eliminar primer nodo')
inst_single_linked_list.delete_at_start()
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('Eliminar nodo por posición')
inst_single_linked_list.remove_node_by_index(3)
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('elimina nodo por valor')
inst_single_linked_list.remove_node_by_value('A')
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('lista al reves')
inst_single_linked_list.reverse_single_linked_list()
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('Obtiene el valor de la mitad de la lista')
inst_single_linked_list.get_value_middle_node()
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('añadir unicamente valores pares al final de la lista')
inst_single_linked_list.add_odd_values_at_end()
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('añadir unicamente valores impares al inicio de la lista')
inst_single_linked_list.add_not_odd_values_at_start()
inst_single_linked_list.print_single_linked_list()
print('--------------------------------------------------------------------')
print('suma todos los valores de la lista')
inst_single_linked_list.get_sum_all_values()
inst_single_linked_list.print_single_linked_list()